language: node_js
node_js:
  - "6"
before_script:
  - 'git config --global user.email "teamshell@nordnet.se"'
  - 'git config --global user.name "nordnet-release"'
after_script:
  - 'npm run coveralls'
after_success:
  - 'npm run semantic-release'
