language: node_js
node_js:
  - "6"
before_script:
  - 'git config --global user.email "gh-pages@localhost"'
  - 'git config --global user.name "npm gh-pages"'
after_script:
  - 'npm run coveralls'
after_success:
  - 'npm run semantic-release'
